package com.proshomon.elasticsearch.nokkhotroelastic.model.model_proshomon.enums;

public enum DisabilityType {
    AUTISM, CHRONIC_ILLNESS, HEARING_LOSS_AND_DEAFNESS, INTELLECTUAL_DISABILITY,
    LEARNING_DISABILITY, MEMORY_LOSS, MENTAL_HEALTH, PHYSICAL_DISABILITY,
    SPEECH_AND_LANGUAGE_DISORDERS, VISION_LOSS_AND_BLINDNESS, NONE
}
