package com.proshomon.elasticsearch.nokkhotroelastic.model.enums;

public enum DisabilityType {
    PHYSICAL, AUTISM, MEMORY_LOSS, MENTAL_HEALTH, INTELLECTUAL_DISABILITY, LEARNING_DISABILITY, PHYSICAL_DISABILITY,
    SPEECH_AND_LANGUAGE_DISORDERS, HEARING_LOSS_AND_DEAFNESS, VISION_LOSS_AND_BLINDNESS, NONE
}
